version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    environment:
      DB_MYSQL_HOST: 'db'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: 'npm'
      DB_MYSQL_PASSWORD: 'acad1a'
      DB_MYSQL_NAME: 'npm'
    volumes:
      - /docker/config/nginx-proxy-manager/config.json:/app/config/production.json
      - /docker/config/nginx-proxy-manager/data:/data
      - /docker/config/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
      - 81:81
    restart: unless-stopped
  db:
    image: linuxserver/mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'acad1a'
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: 'acad1a'
      PUID: 1000
      PGID: 1000
      TZ: 'America/Costa_Rica'

    volumes:
      - /docker/config/nginx-proxy-manager/database:/config